# Don't print a new line at the start of the prompt
add_newline = false

# Wait milliseconds for starship to check files under the current dir (default: 30)
scan_timeout = 10

[line_break]
disabled = true

[battery]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[gcloud]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[php]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true
